const dataProjects = [{
  imgUrl: './media/Snapshoot-Portfolio.png',
  imgUrlDesktop: './media/snapshoot-portfolio-desktop.png',
  projectTitle: 'Keeping track of hundreds of components #1',
  projectTitleDesktop: 'Multi-Post Stories Gain+Glory',
  tags: ['Ruby on Rails', 'JavaScript', 'CSS'],
  text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto ullam repudiandae nesciunt natus vitae a commodi, dicta optio ex dolor amet quo odio nam voluptatum magnam repellendus deleniti veritatis obcaecati? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus distinctio maiores, reiciendis tempora asperiores nulla odit quo vero veritatis ex magnam quos, alias, ipsa officia. Voluptate doloremque natus iste maiores!',
  liveUrl: 'dredwell.github.io/my-portfolio',
  sourceUrl: 'https://github.com/Dredwell/my-portfolio',
},
{
  imgUrl: './media/Snapshoot-Portfolio.png',
  imgUrlDesktop: './media/snapshoot-portfolio-desktop.png',
  projectTitle: 'Keeping track of hundreds of components #2',
  projectTitleDesktop: 'Multi-Post Stories Gain+Glory',
  tags: ['Ruby on Rails', 'JavaScript', 'CSS', 'HTML'],
  text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto ullam repudiandae nesciunt natus vitae a commodi, dicta optio ex dolor amet quo odio nam voluptatum magnam repellendus deleniti veritatis obcaecati?',
  liveUrl: 'dredwell.github.io/my-portfolio',
  sourceUrl: 'https://github.com/Dredwell/my-portfolio',
},
{
  imgUrl: './media/Snapshoot-Portfolio.png',
  imgUrlDesktop: './media/snapshoot-portfolio-desktop.png',
  projectTitle: 'Keeping track of hundreds of components #3',
  projectTitleDesktop: 'Multi-Post Stories Gain+Glory',
  tags: ['Ruby on Rails', 'JavaScript', 'CSS', 'Ruby'],
  text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto ullam repudiandae nesciunt natus vitae a commodi, dicta optio ex dolor amet quo odio nam voluptatum magnam repellendus deleniti veritatis obcaecati? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus distinctio maiores, reiciendis tempora asperiores nulla odit quo vero veritatis ex magnam quos, alias, ipsa officia. Voluptate doloremque natus iste maiores!',
  liveUrl: 'dredwell.github.io/my-portfolio',
  sourceUrl: 'https://github.com/Dredwell/my-portfolio',
},
{
  imgUrl: './media/Snapshoot-Portfolio.png',
  imgUrlDesktop: './media/snapshoot-portfolio-desktop.png',
  projectTitle: 'Keeping track of hundreds of components #4',
  projectTitleDesktop: 'Multi-Post Stories Gain+Glory',
  tags: ['Ruby on Rails', 'JavaScript', 'CSS'],
  text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto ullam repudiandae nesciunt natus vitae a commodi, dicta optio ex dolor amet quo odio nam voluptatum magnam repellendus deleniti veritatis obcaecati? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus distinctio maiores, reiciendis tempora asperiores nulla odit quo vero veritatis ex magnam quos, alias, ipsa officia. Voluptate doloremque natus iste maiores!',
  liveUrl: 'dredwell.github.io/my-portfolio',
  sourceUrl: 'https://github.com/Dredwell/my-portfolio',
},
{
  imgUrl: './media/Snapshoot-Portfolio.png',
  imgUrlDesktop: './media/snapshoot-portfolio-desktop.png',
  projectTitle: 'Keeping track of hundreds of components #5',
  projectTitleDesktop: 'Multi-Post Stories Gain+Glory',
  tags: ['Ruby on Rails', 'JavaScript', 'CSS'],
  text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto ullam repudiandae nesciunt natus vitae a commodi, dicta optio ex dolor amet quo odio nam voluptatum magnam repellendus deleniti veritatis obcaecati?',
  liveUrl: 'dredwell.github.io/my-portfolio',
  sourceUrl: 'https://github.com/Dredwell/my-portfolio',
},
{
  imgUrl: './media/Snapshoot-Portfolio.png',
  imgUrlDesktop: './media/snapshoot-portfolio-desktop.png',
  projectTitle: 'Keeping track of hundreds of components #6',
  projectTitleDesktop: 'Multi-Post Stories Gain+Glory',
  tags: ['Ruby on Rails', 'JavaScript', 'CSS'],
  text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto ullam repudiandae nesciunt natus vitae a commodi, dicta optio ex dolor amet quo odio nam voluptatum magnam repellendus deleniti veritatis obcaecati?',
  liveUrl: 'dredwell.github.io/my-portfolio',
  sourceUrl: 'https://github.com/Dredwell/my-portfolio',
}];

export default dataProjects;